//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarden.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Cocuk
    {
        [DisplayName("Ad : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]
       
        public string Cad { get; set; }
        [DisplayName("Soyad : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]
        public string Csoyad { get; set; }
        [DisplayName("Cinsiyet : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]
        public string Ccinsiyet { get; set; }
        [DisplayName("Yaþ : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]
        public string Cyas { get; set; }
        [DisplayName("Veli adý : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]
        public string Cveliadi { get; set; }
    }
}
