//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarden.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Mesaj
    {
        [DisplayName("E-mail : ")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Geçerli bir e-mail adresi giriniz.")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]

        public string Email { get; set; }

        [DisplayName("Etkinlik : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]

        public string Etkinlik { get; set; }

        [DisplayName("Yemek : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]

        public string Yemek { get; set; }

        [DisplayName("Geldi mi :")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]

        public string GeldiMi { get; set; }

        [DisplayName("Diðer mesaj : ")]
        public string Others { get; set; }
    }
}
