//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarden.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [DisplayName("Ad : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]

        public string Ad { get; set; }

        [DisplayName("Soyad : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]

        public string Soyad { get; set; }

        [DisplayName("E-mail : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Geçerli bir e-mail adresi giriniz.")]
        public string Email { get; set; }

        [DisplayName("Þifre : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]

        public string Sifre { get; set; }

        [DisplayName("Telefon : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]

        public string Tel { get; set; }

        [DisplayName("Çocuðunuzun adý : ")]
        public string CocukAdi { get; set; }

        [DisplayName("Öðretmen misiniz? : ")]
        [Required(ErrorMessage = "Bu alaný boþ býrakamazsýnýz.")]

        public string Admin { get; set; }
    }
}
